version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "friday"
      time: "18:00"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps)"
      include: "scope"
