# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "nvisy-pattern"
version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = "./README.md"

authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }

[features]
default = []

[dev-dependencies]
serde_json = "1.0"
